/******************************************************************************
 *    Student: Mathew Yamasaki
 *       Date: Tuesday, May 15, 2012
 *      Class: Object Oriented and Concurrent Programming (CMSC 335)
 * Instructor: Dr. Mihaela Dinsoreanu
 *        JVM: 1.6
 * 
 * Class Description: This class creates the GUI that allows users to borrow and
 * return books.
 ******************************************************************************/

package cmsc335_final_project;

import cmsc335_final_project.LibraryManager.ReturnTask;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import javax.swing.JOptionPane;

/**
 *
 * @author Max
 */
public class BookBorrowAndReturnGUI extends javax.swing.JFrame {

    static LibraryManager lfq = new LibraryManager();
    
    /**
     * Creates new form BookBorrowAndReturnGUI
     */
    public BookBorrowAndReturnGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        borrowButton = new javax.swing.JButton();
        returnButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Borrow or return a book");

        jLabel1.setText("Title");

        borrowButton.setText("Borrow");
        borrowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrowButtonActionPerformed(evt);
            }
        });

        returnButton.setText("Return");
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(titleField, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(borrowButton)
                        .addGap(38, 38, 38)
                        .addComponent(returnButton)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(borrowButton)
                    .addComponent(returnButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void borrowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrowButtonActionPerformed
        ExecutorService borrowExecutor = Executors.newCachedThreadPool();
        LibraryManager.BorrowTask bt = lfq.new BorrowTask();
        bt.getBorrowTitle(titleField.getText().trim());

        borrowExecutor.execute(bt);
        
        borrowExecutor.shutdown();
   
        while (!borrowExecutor.isTerminated()) {
            
        }
        
        JOptionPane.showMessageDialog(null, titleField.getText() + 
                " has been borrowed", "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_borrowButtonActionPerformed

    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
        ExecutorService returnExecutor = Executors.newCachedThreadPool();
        LibraryManager.ReturnTask bt = lfq.new ReturnTask();
        
        bt.getReturnTitle(titleField.getText().trim());

        returnExecutor.execute(bt);
        
        returnExecutor.shutdown();
        
        while (!returnExecutor.isTerminated()) {
           
        }
        
        JOptionPane.showMessageDialog(null, titleField.getText() + 
                " has been returned", "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_returnButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrowButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton returnButton;
    private javax.swing.JTextField titleField;
    // End of variables declaration//GEN-END:variables
}
