/******************************************************************************
 *    Student: Mathew Yamasaki
 *       Date: Tuesday, May 15, 2012
 *      Class: Object Oriented and Concurrent Programming (CMSC 335)
 * Instructor: Dr. Mihaela Dinsoreanu
 *        JVM: 1.6
 * 
 * Class Description: Creates the GUI and connects buttons and fields to 
 * appropriate methods of the Library class.
 ******************************************************************************/

package cmsc335_final_project;

import cmsc335_final_project.JTableLibraryView.IndexComparator;
import cmsc335_final_project.JTableLibraryView.PriceComparator;
import java.awt.BorderLayout;
import java.util.Vector;
import javax.swing.*;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.tree.DefaultMutableTreeNode;

public class LibraryGUI extends javax.swing.JFrame {

    // instantiate objects
    Library l = new Library();
    Book b = new Book();
    
    // variable declarations
    private int _jBookIndex;
    private String _jBookTitle;
    private String _jGenre;
    private int _jAuthorIndex;

    /** Creates new form NewJFrame1 */
    public LibraryGUI() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        bookIndexSearchRadioButton = new javax.swing.JRadioButton();
        titleSearchRadioButton = new javax.swing.JRadioButton();
        genreSearchRadioButton = new javax.swing.JRadioButton();
        authorIndexSearchRadioButton = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        searchField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        searchResultsDisplay = new javax.swing.JTextArea();
        displayTable = new javax.swing.JButton();
        showTree = new javax.swing.JButton();
        borrowJButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Welcome to the library!");

        jLabel1.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 36)); // NOI18N
        jLabel1.setText("Library Search");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        buttonGroup1.add(bookIndexSearchRadioButton);
        bookIndexSearchRadioButton.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 13)); // NOI18N
        bookIndexSearchRadioButton.setText("Book Index");

        buttonGroup1.add(titleSearchRadioButton);
        titleSearchRadioButton.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 13)); // NOI18N
        titleSearchRadioButton.setText("Title");

        buttonGroup1.add(genreSearchRadioButton);
        genreSearchRadioButton.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 13)); // NOI18N
        genreSearchRadioButton.setText("Genre");

        buttonGroup1.add(authorIndexSearchRadioButton);
        authorIndexSearchRadioButton.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 13)); // NOI18N
        authorIndexSearchRadioButton.setText("Author Index");

        jLabel2.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 13)); // NOI18N
        jLabel2.setText("Search by:");

        searchField.setToolTipText("");
        searchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFieldActionPerformed(evt);
            }
        });

        searchButton.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 13)); // NOI18N
        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 13)); // NOI18N
        jLabel3.setText("Enter search term:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(authorIndexSearchRadioButton)
                            .addComponent(titleSearchRadioButton)
                            .addComponent(bookIndexSearchRadioButton)
                            .addComponent(genreSearchRadioButton)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(searchButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(searchField, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(bookIndexSearchRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titleSearchRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(genreSearchRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(authorIndexSearchRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        searchResultsDisplay.setColumns(20);
        searchResultsDisplay.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 14)); // NOI18N
        searchResultsDisplay.setRows(5);
        jScrollPane1.setViewportView(searchResultsDisplay);

        displayTable.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 24)); // NOI18N
        displayTable.setText("Show Inventory");
        displayTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayTableActionPerformed(evt);
            }
        });

        showTree.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 24)); // NOI18N
        showTree.setText("Tree View");
        showTree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showTreeActionPerformed(evt);
            }
        });

        borrowJButton.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 24)); // NOI18N
        borrowJButton.setText("Manage Inventory");
        borrowJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrowJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(displayTable)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(showTree)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(borrowJButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(displayTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(showTree, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(borrowJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /** make appropriate methods call for a selected radio button after user strikes 'Enter' key */
    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
       
        if (bookIndexSearchRadioButton.isSelected()) {
            try {
                _jBookIndex = Integer.parseInt(this.searchField.getText());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Please enter a numeric value",
                        "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            searchResultsDisplay.setText(l.bookMapIterator(Library.bookMap, _jBookIndex));
        }
        if (titleSearchRadioButton.isSelected()) {
            _jBookTitle = this.searchField.getText();
            searchResultsDisplay.setText(l.getInfoFromTitle(Library.books, 
                    Library.authors, _jBookTitle));
        }
        if (genreSearchRadioButton.isSelected()) {
            _jGenre = this.searchField.getText();
            l.getTitleFromGenre(Library.books, _jGenre, searchResultsDisplay);
        }
        if (authorIndexSearchRadioButton.isSelected()) {
            try {
            _jAuthorIndex = Integer.parseInt(this.searchField.getText());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Please enter a number",
                        "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            searchResultsDisplay.setText(l.authorMapIterator(l.authorMap, _jAuthorIndex));
        }
    }//GEN-LAST:event_searchFieldActionPerformed

    /** make appropriate method calls for selected radio button after user clicks search button */
    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed

        if (bookIndexSearchRadioButton.isSelected()) {
            try {
                _jBookIndex = Integer.parseInt(this.searchField.getText());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Please enter a numeric value",
                        "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            searchResultsDisplay.setText(l.bookMapIterator(Library.bookMap, _jBookIndex));
        }
        if (titleSearchRadioButton.isSelected()) {
            _jBookTitle = this.searchField.getText();
            searchResultsDisplay.setText(l.getInfoFromTitle(Library.books, 
                    Library.authors, _jBookTitle));
        }
        if (genreSearchRadioButton.isSelected()) {
            _jGenre = this.searchField.getText();
            l.getTitleFromGenre(Library.books, _jGenre, searchResultsDisplay);
        }
        if (authorIndexSearchRadioButton.isSelected()) {
            try {
            _jAuthorIndex = Integer.parseInt(this.searchField.getText());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Please enter a number",
                        "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            searchResultsDisplay.setText(l.authorMapIterator(l.authorMap, _jAuthorIndex));
        }
    }//GEN-LAST:event_searchButtonActionPerformed

   
    /** displays a scroll pane with a table containing the library's contents */
    private void displayTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayTableActionPerformed

        // create vector and add column titles
        Vector columnNames = new Vector();
        columnNames.add("Index");
        columnNames.add("Title");
        columnNames.add("Author");
        columnNames.add("Genre");
        columnNames.add("Price");
        columnNames.add("Copies Available");

        // create table 
        JTable jTable2 = new JTable(JTableLibraryView.rowData, columnNames);
        //jTable2.setAutoResizeMode(jTable2.AUTO_RESIZE_OFF);
        jTable2.getColumnModel().getColumn(0).setPreferredWidth(10);
        //jTable2.getColumnModel().getColumn(1).setPreferredWidth(150);
        jTable2.getColumnModel().getColumn(2).setPreferredWidth(120);
        
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        jTable2.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
        jTable2.getColumnModel().getColumn(5).setCellRenderer(centerRenderer);
        
        
        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(JLabel.RIGHT);
        jTable2.getColumnModel().getColumn(4).setCellRenderer(rightRenderer);
        
        // set table model
        DefaultTableModel tableModel = new DefaultTableModel(JTableLibraryView.rowData, columnNames);
        
        // set row sorter 
        TableRowSorter trs = new TableRowSorter(tableModel);
 
        // instantiate inner class Comparator for book indices
        IndexComparator indexComparator = new JTableLibraryView().new IndexComparator();
        
        // instantiate inner class Comparator for book prices
        PriceComparator priceComparator = new JTableLibraryView().new PriceComparator();
        
        // set column 0 to use indexComparator for integer values
        trs.setComparator(0, indexComparator);
  
        // set column 3 to use priceComparator for double values
        trs.setComparator(4, priceComparator); 
        
        // set row sorter for table
        jTable2.setRowSorter(trs);
        
        // add table to scroll pane
        JScrollPane tableScrollPane = new JScrollPane(jTable2);
        jTable2.setAutoCreateRowSorter(false);
        
        // create table JFrame and set properties
        JTableLibraryView tableFrame = new JTableLibraryView();
        tableFrame.add(tableScrollPane, BorderLayout.CENTER);;
        tableFrame.setVisible(true);
    }//GEN-LAST:event_displayTableActionPerformed
    
    /** displays a scroll pane with a tree view of the library's contents */
    private void showTreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showTreeActionPerformed
        
        // instantiate objects
        DefaultMutableTreeNode top = new DefaultMutableTreeNode("Genres");
        TreeNodeCreator tnc = new TreeNodeCreator();
        JTree tree = new JTree(top);
        
        // method to add nodes to the top node
        tnc.nodeAdder(top);

        // create scroll pane
        JScrollPane treeScrollPane = new JScrollPane(tree);
        
        // add tree to JFrame
        tnc.add(treeScrollPane, BorderLayout.CENTER);
        tnc.setVisible(true);
    }//GEN-LAST:event_showTreeActionPerformed

    private void borrowJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrowJButtonActionPerformed
        
        BookBorrowAndReturnGUI bar = new BookBorrowAndReturnGUI();
        bar.setLocationRelativeTo(null);
        bar.setVisible(true);
        
    }//GEN-LAST:event_borrowJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton authorIndexSearchRadioButton;
    private javax.swing.JRadioButton bookIndexSearchRadioButton;
    private javax.swing.JButton borrowJButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton displayTable;
    private javax.swing.JRadioButton genreSearchRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchField;
    private javax.swing.JTextArea searchResultsDisplay;
    private javax.swing.JButton showTree;
    private javax.swing.JRadioButton titleSearchRadioButton;
    // End of variables declaration//GEN-END:variables
}
